#ifndef RISCV_INSTRUCTION_CYCLE_COUNTS
#define RISCV_INSTRUCTION_CYCLE_COUNTS

#define ADD_CYCLE_COUNT 1
#define MUL_CYCLE_COUNT 4
#define SUB_CYCLE_COUNT 1
#define SLL_CYCLE_COUNT 1
#define MULH_CYCLE_COUNT 5
#define SLT_CYCLE_COUNT 1
#define MULHSU_CYCLE_COUNT 5
#define SLTU_CYCLE_COUNT 1
#define MULHU_CYCLE_COUNT 5
#define XOR_CYCLE_COUNT 1
#define DIV_CYCLE_COUNT 32
#define SRL_CYCLE_COUNT 1
#define SRA_CYCLE_COUNT 1
#define DIVU_CYCLE_COUNT 32
#define OR_CYCLE_COUNT 1
#define REM_CYCLE_COUNT 32
#define AND_CYCLE_COUNT 1
#define REMU_CYCLE_COUNT 32

/* I-Type Instructions */
#define JALR_CYCLE_COUNT 1

#define ADDI_CYCLE_COUNT 1
#define SLTI_CYCLE_COUNT 1
#define SLTIU_CYCLE_COUNT 1
#define XORI_CYCLE_COUNT 1
#define ORI_CYCLE_COUNT 1
#define ANDI_CYCLE_COUNT 1
#define SLLI_CYCLE_COUNT 1
#define SRLI_CYCLE_COUNT 1
#define SRAI_CYCLE_COUNT 1
#define SRLI_CYCLE_COUNT 1
#define SRAI_CYCLE_COUNT 1

#define LB_CYCLE_COUNT 3
#define LH_CYCLE_COUNT 3
#define LW_CYCLE_COUNT 2
#define LBU_CYCLE_COUNT 3
#define LHU_CYCLE_COUNT 3
#define LWU_CYCLE_COUNT 2
#define LD_CYCLE_COUNT 2

#define SB_CYCLE_COUNT 1
#define SH_CYCLE_COUNT 1
#define SW_CYCLE_COUNT 1
#define SD_CYCLE_COUNT 1

#define BEQ_CYCLE_COUNT 1
#define BNE_CYCLE_COUNT 1
#define BLT_CYCLE_COUNT 1
#define BGE_CYCLE_COUNT 1
#define BLTU_CYCLE_COUNT 1
#define BGEU_CYCLE_COUNT 1

/* U-Type Instructions */
#define LUI_CYCLE_COUNT 1   /* LOAD UPPER IMMEDIATE INTO DESTINATION REGISTER */
#define AUIPC_CYCLE_COUNT 1 /* ADD UPPER IMMEDIATE TO PROGRAM COUNTER */

/* J-Type Instructions */
#define JAL_CYCLE_COUNT 1   /* JUMP and Link */

/* System level instructions */
#define FENCE_CYCLE_COUNT 5
#define FENCE_I_CYCLE_COUNT 5


#define ECALL_CYCLE_COUNT 20
#define EBREAK_CYCLE_COUNT 20
#define URET_CYCLE_COUNT 20
#define SRET_CYCLE_COUNT 20
#define WFI_CYCLE_COUNT 1
#define MRET_CYCLE_COUNT 20
#define SFENCEVMA_CYCLE_COUNT 10
#define CSRRW_CYCLE_COUNT 3
#define CSRRS_CYCLE_COUNT 3
#define CSRRC_CYCLE_COUNT 3
#define CSRRWI_CYCLE_COUNT 3
#define CSRRSI_CYCLE_COUNT 3
#define CSRRCI_CYCLE_COUNT 3

#define SLLIW_CYCLE_COUNT 1
#define SRLIW_CYCLE_COUNT 1
#define SRAIW_CYCLE_COUNT 1
#define ADDIW_CYCLE_COUNT 1

#define ADDW_CYCLE_COUNT 1
#define SUBW_CYCLE_COUNT 1
#define MULW_CYCLE_COUNT 5
#define SLLW_CYCLE_COUNT 1
#define DIVW_CYCLE_COUNT 32
#define SRLW_CYCLE_COUNT 1
#define SRAW_CYCLE_COUNT 1
#define DIVUW_CYCLE_COUNT 32
#define REMW_CYCLE_COUNT 32
#define REMUW_CYCLE_COUNT 32

/* Atomic Instructions */

#define AMO_LR_CYCLE_COUNT 0x2
#define AMO_SC_CYCLE_COUNT 0x3
#define AMO_SWAP_CYCLE_COUNT 0x1
#define AMO_ADD_CYCLE_COUNT 0x0
#define AMO_XOR_CYCLE_COUNT 0x4
#define AMO_AND_CYCLE_COUNT 0xC
#define AMO_OR_CYCLE_COUNT 0x8
#define AMO_MIN_CYCLE_COUNT 0x10
#define AMO_MAX_CYCLE_COUNT 0x14
#define AMO_MINU_CYCLE_COUNT 0x18
#define AMO_MAXU_CYCLE_COUNT 0x1C

#define FLT_ADD_CYCLE_COUNT 4
#define FLT_SUB_CYCLE_COUNT 4
#define FLT_MUL_CYCLE_COUNT 4
#define FLT_DIV_CYCLE_COUNT 20
#define FLT_SQRT_CYCLE_COUNT 20
#define FLT_SGNINJ_CYCLE_COUNT 4
#define FLT_SGNJ_CYCLE_COUNT 4
#define FLT_SGNJN_CYCLE_COUNT 4
#define FLT_SGNJX_CYCLE_COUNT 4
#define FLT_MIN_CYCLE_COUNT 4
#define FLT_MAX_CYCLE_COUNT 4
#define FLT_CMPEQ_CYCLE_COUNT 4
#define FLT_CMPLT_CYCLE_COUNT 4
#define FLT_CMPLE_CYCLE_COUNT 4
#define FLT_CVT_TO_SINT_CYCLE_COUNT 4
#define FLT_CVT_TO_UINT_CYCLE_COUNT 4
#define FLT_CVT_TO_LONG_CYCLE_COUNT 4
#define FLT_CVT_TO_ULONG_CYCLE_COUNT 4
#define FLT_CVT_FROM_SINT_CYCLE_COUNT 4
#define FLT_CVT_FROM_UINT_CYCLE_COUNT 4
#define FLT_CVT_FROM_LONG_CYCLE_COUNT 4
#define FLT_CVT_FROM_ULONG_CYCLE_COUNT 4
#define FLT_MV_TO_INT_CYCLE_COUNT 4
#define FLT_MV_FROM_INT_CYCLE_COUNT 4

#define FLT_LOAD_CYCLE_COUNT 3
#define FLT_STORE_CYCLE_COUNT 3

#define FMADD_CYCLE_COUNT 24
#define FMSUB_CYCLE_COUNT 24
#define FMNSUB_CYCLE_COUNT 24
#define FMNADD_CYCLE_COUNT 24


#define LR_READ_CYCLE_COUNT 1
#define LWRITE_CYCLE_COUNT 1
#define LTRIM_CYCLE_COUNT 1
#define PREAD_CYCLE_COUNT 1
#define PWRITE_CYCLE_COUNT 1
#define PERASE_CYCLE_COUNT 1
#define READBUFF_CYCLE_COUNT 1
#define STARTSIM_CYCLE_COUNT 1 // stop continuos execution
#define STOPSIM_CYCLE_COUNT 1 // execute once every cycle
#define NEXTSIMTICK_CYCLE_COUNT 1 // sets the next tick
#define PUTC_CYCLE_COUNT 1
#define WRITEBUFF_CYCLE_COUNT 1

#endif